name: Create release

permissions:
  contents: write
  id-token: write

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:
    uses: ./.github/workflows/testing.yml

  Publish:
    needs: [Test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

  build:
    needs: [Test, Publish]
    runs-on: ${{ matrix.runner }}
    env:
      BINARY_NAME: rusk
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            extension: ""
            runner: ubuntu-latest
            cross: true
          - target: x86_64-pc-windows-msvc
            extension: ".exe"
            runner: windows-latest
            cross: false
          - target: x86_64-apple-darwin
            extension: ""
            runner: macos-latest
            cross: false
          - target: aarch64-unknown-linux-gnu
            extension: ""
            runner: ubuntu-latest
            cross: true
          - target: aarch64-pc-windows-msvc
            extension: ".exe"
            runner: windows-latest
            cross: false
          - target: aarch64-apple-darwin
            extension: ""
            runner: macos-latest
            cross: false
          - target: armv7-unknown-linux-gnueabihf
            extension: ""
            runner: ubuntu-latest
            cross: true

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Dependencies on Windows
        if: ${{ matrix.runner == 'windows-latest' }}
        run: |
          choco install make tar --yes
      - name: Install Dependencies on MacOS
        if: ${{ matrix.runner == 'macos-latest' }}
        run: |
          brew install make

      - name: Install cross (if needed)
        if: ${{ matrix.cross }}
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build Project on cross
        if: ${{ matrix.cross }}
        run: |
          cross build --release --target ${{ matrix.target }} --verbose
      - name: Build Project
        if: ${{ !matrix.cross }}
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release --target ${{ matrix.target }} --verbose

      - name: Create tarball
        shell: bash
        run: |
          tar -czvf ${{ env.BINARY_NAME }}-${{ github.ref_name }}-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release ${{ env.BINARY_NAME }}${{ matrix.extension }}

      - name: Release Artifacts
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ env.BINARY_NAME }}-${{ github.ref_name }}-${{ matrix.target }}.tar.gz
